apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-server-config
  labels:
    name: loki-server-config
  namespace: monitoring
data:
  loki.yaml: |-
    auth_enabled: false

    server:
      http_listen_port: 3100
      log_level: warn

    memberlist:
      abort_if_cluster_join_fails: false
      # Expose this port on all distributor, ingester and querier replicas
      bind_port: 7946

      # you can use a headless k8s service for all distributor, ingester and querier components.
      join_members:
      - loki.monitoring.svc.cluster.local:7946
      
      max_join_backoff: 1m
      max_join_retries: 10
      min_join_backoff: 1s

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_block_size: 262144
      chunk_retain_period: 30s
      max_chunk_age: 10m
      max_transfer_retries: 0

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h # 1 week

    compactor:
      working_directory: /loki/boltdb-shipper/compactor
      shared_store: s3
      compaction_interval: 5m

    schema_config:
      configs:
      # schema config 적용 시작 날짜. 날짜 기반으로 schema config 변경 가능
      - from: 2021-05-01
        store: boltdb-shipper
        object_store: aws
        schema: v11
        index:
          prefix: loki_index_
          period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/boltdb-shipper/active
        cache_location: /loki/boltdb-shipper/cache
        cache_ttl: 24h
        shared_store: s3
      aws:
        bucketnames: gf-loki
        endpoint: rgw.sungup.io:8080
        region: default
        access_key_id: NN2DTW3WALH1MH9BGHKZ
        secret_access_key: GWjENcoy5xGYGJ8rmnNC6lToPSMeyk9NCoRFEuez 
        insecure: true
        sse_encryption: false
        http_config:
          idle_conn_timeout: 90s
          response_header_timeout: 0s
          insecure_skip_verify: false
        s3forcepathstyle: true

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: true
      retention_period: 182d # 반년으로 구성. 단, 이 값은 period로 나누어 떨어져야 함.