apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '3100'
spec:
  type: LoadBalancer
  selector:
    app: loki-server
  ports:
  - name: loki-http
    port: 3100
    targetPort: loki-http
  - name: gossip-ring
    port: 7946
    targetPort: gossip-ring

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: monitoring
spec:
  serviceName: loki
  replicas: 3
  selector:
    matchLabels:
      app: loki-server
  template:
    metadata:
      labels:
        app: loki-server
    spec:
      containers:
      - name: grafana
        image: grafana/loki:2.2.1
        args:
        - "--config.file=/etc/loki/loki.yaml"
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
        ports:
        - name: loki-http
          containerPort: 3100
        - name: gossip-ring
          containerPort: 7946
        securityContext:
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
        readinessProbe:
          httpGet:
            path: /ready
            port: 3100
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3100
          initialDelaySeconds: 30
          periodSeconds: 30
        volumeMounts:
        - name: loki-conf-vol
          mountPath: /etc/loki
        - name: loki-data-vol
          mountPath: /loki
      volumes:
      - name: loki-conf-vol
        configMap:
          defaultMode: 420
          name: loki-server-config

  volumeClaimTemplates:
  - metadata:
      name: loki-data-vol
      namespace: monitoring
    spec:
      storageClassName: csi-rbd-sc
      volumeMode: Filesystem
      accessModes: 
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 50Gi
