apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3100'
spec:
  type: LoadBalancer
  selector:
    app: loki-server
  ports:
  - port: 3100
    targetPort: loki-http
