apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-model1-bm1
spec:
  storageClassName: sc-model1
  resources:
    requests:
      storage: 4Gi
  volumeMode: Block
  accessModes:
  - ReadWriteOnce

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-model1-bm2
spec:
  storageClassName: sc-model1
  resources:
    requests:
      storage: 4Gi
  volumeMode: Block
  accessModes:
  - ReadWriteOnce