# DOC: https://grafana.com/docs/grafana/latest/installation/kubernetes/

apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: http-grafana
  selector:
    app: grafana-server
  sessionAffinity: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: monitoring
spec:
  serviceName: grafana
  replicas: 1
  selector:
    matchLabels:
      app: grafana-server
  template:
    metadata:
      labels:
        app: grafana-server
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:7.5.5
        ports:
        - containerPort: 3000
          name: http-grafana
        readinessProbe:
          failureThreshold: 3
          httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-data-vol
  volumeClaimTemplates:
  - metadata:
      name: grafana-data-vol
      namespace: monitoring
    spec:
      storageClassName: csi-rbd-sc
      volumeMode: Filesystem
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
