apiVersion: v1
kind: Secret
metadata:
  name: ceph-admin-secret
  namespace: kube-system
data:
  key: QVFDQ05JVmd1V2RBRXhBQUc1Y2VCeDJDdXBlQnVwc0tESUxaMUE9PQ==
type: kubernetes.io/rbd

---

apiVersion: v1
kind: Secret
metadata:
  name: ceph-user-secret
  namespace: kube-system
data:
  key: QVFCSVVZNWdHUm9QQnhBQXNuK3UxMFdDZkZuWFlHcDJNSWdjc3c9PQ==
type: kubernetes.io/rbd
