apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  # Storage Class name
  name: ceph-rbd
provisioner: ceph.com/rbd
parameters:
  # Ceph MON address & pool name
  monitor: 10.0.1.21:6789
  pool: k8s

  # Ceph admin account information
  adminId: admin
  adminSecretNamespace: kube-system
  adminSecretName: ceph-admin-secret
  
  # Ceph user account information
  userId: kube
  userSecretNamespace: kube-system
  userSecretName: ceph-user-secret

  # Following options should be check the rbd man page
  # http://manpages.ubuntu.com/manpages/xenial/man8/rbd.8.html
  # Image format 2 (1 had been deprecated)
  imageFormat: "2"
  # Image feature
  imageFeature: layering
