apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-rbd-test-pvc
spec:
  # Ceph RBD 구성의 경우 Dynamic Provisioning을 활용하기 때문에 Storage Class 만
  # 지정해 주면 해당 Storage Class에 PVC를 위한 Volume을 동적으로 생성해 관리하기
  # 때문에 별도의 PV 설정을 필요로 하지 않음. PV를 활용하는 경우는, Static
  # Provisioning 시에서 활용하는 방법임.
  storageClassName: ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi