

apiVersion: v1
kind: Pod
metadata:
  name: ceph-rbd-test-pod
  labels:
    name: ceph-rbd-test-pod
spec:
  containers:
  - name: ceph-rbd-test-pod
    image: busybox
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "while true; do touch /mnt/RBD-SUCCESS-$(date +%Y%m%d%H%M%S) && sleep 10; done" 
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: test-pvc
      mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
  - name: test-pvc
    persistentVolumeClaim:
      claimName: ceph-rbd-test-pvc
